# Generated by Django 6.1.1 on 2026-09-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
